### ISSUE TITLE
SVG & HTML output

### ISSUE THREAD

**Issue by sarah872** [bjtully/BioData#19]
Hi again.
As you mentioned in the last issue, I re-did the analysis using two genomes (Kofamscan run on two genomes separately (with headers like Prefix_sequentialnumber) and concatenate the two KO lists).
Concerning the `svg` output: Besides that the colors are not red instead of blue (I prefer blue ;-) ), There is no legend drawn with the command `-v static`. However, when I run the decode/expand code with  `KEGG_expander.py`, the legend IS drawn.
Concerning the `html` output: This file looks faulty. The function names are all cropped and only one genome is displayed, without any heatmap. Have a look at the screenshot of part of the html file. If you need the files let me know.

![Screenshot 2019-05-16 10 35 20](https://user-images.githubusercontent.com/29072882/57839171-757f0780-77c6-11e9-960e-585c5f54b233.png)

**Comment by bjtully** [comment]
The legend is a work in progress - as you can see when you run KEGG_expander, the default output is huge. It's been temporarily removed in static mode until it can be addressed.

The interactive mode will also require submitting at least two genomes, again because of the new added feature to clustering the metabolism result. I'll be sure to modify that as well in the next update.

**Comment by sarah872** [comment]
The legend is not a big issue, I made a printable version in Illustrator that I can easily add.

For the interactive mode, I did submit two genomes. However only 1 is shown, and even there the functions are not showing up.

**Comment by bjtully** [comment]
The legend for the static image should now be present (and manageable in size). And due the necessary space to visualize the 'interactive' mode, it has been set to only be used for >=50 genomes.
