### ISSUE TITLE
about the KEGG_decoder.py

### ISSUE THREAD

**Issue by caris1988** [bjtully/BioData#52]
Hello! I think the KEGG-Decoder is very useful. But it seem that there is a typo in the script KEGG_decoder.py.

line265-266
```
#citryl-CoA synthetase AND citryl-CoA lyase
	if ('K15232' in ko_match and 'K15232' in ko_match and 'K15234' in ko_match):
```
One of the K15232 should be K15233. And, in my opinion, it is better to define this enzyme as:

` if (('K15232' in ko_match or 'K15233' in ko_match) and 'K15234' in ko_match):`

What do you think about it?

Best regards,
Cheng

**Comment by bjtully** [comment]
Great find, @caris1988!

I have made the correction. But I did not change the enzyme definition as you suggested. I don't think the OR statement to check for K15232 or K15233 is appropriate, as they are subunits of the same enzyme. I am intentionally trying to be conservative in calling reverse TCA, just because of the low threshold it takes to go from heterotroph to autotroph in that instance.

If you have any info. that would suggest K15233 isn't necessary for a functioning citryl-CoA synthetase please send it may way and I'll adjust accordingly.
